// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/media.proto

package serializers.protobuf.media;

public final class MediaContentHolder {
  private MediaContentHolder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ImageOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string uri = 1;
    boolean hasUri();
    String getUri();
    
    // optional string title = 2;
    boolean hasTitle();
    String getTitle();
    
    // required int32 width = 3;
    boolean hasWidth();
    int getWidth();
    
    // required int32 height = 4;
    boolean hasHeight();
    int getHeight();
    
    // required .serializers.protobuf.media.Image.Size size = 5;
    boolean hasSize();
    serializers.protobuf.media.MediaContentHolder.Image.Size getSize();
  }
  public static final class Image extends
      com.google.protobuf.GeneratedMessageLite
      implements ImageOrBuilder {
    // Use Image.newBuilder() to construct.
    private Image(Builder builder) {
      super(builder);
    }
    private Image(boolean noInit) {}
    
    private static final Image defaultInstance;
    public static Image getDefaultInstance() {
      return defaultInstance;
    }
    
    public Image getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum Size
        implements com.google.protobuf.Internal.EnumLite {
      SMALL(0, 0),
      LARGE(1, 1),
      ;
      
      public static final int SMALL_VALUE = 0;
      public static final int LARGE_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Size valueOf(int value) {
        switch (value) {
          case 0: return SMALL;
          case 1: return LARGE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Size>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Size>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Size>() {
              public Size findValueByNumber(int number) {
                return Size.valueOf(number);
              }
            };
      
      private final int value;
      
      private Size(int index, int value) {
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:serializers.protobuf.media.Image.Size)
    }
    
    private int bitField0_;
    // required string uri = 1;
    public static final int URI_FIELD_NUMBER = 1;
    private java.lang.Object uri_;
    public boolean hasUri() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uri_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 width = 3;
    public static final int WIDTH_FIELD_NUMBER = 3;
    private int width_;
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getWidth() {
      return width_;
    }
    
    // required int32 height = 4;
    public static final int HEIGHT_FIELD_NUMBER = 4;
    private int height_;
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getHeight() {
      return height_;
    }
    
    // required .serializers.protobuf.media.Image.Size size = 5;
    public static final int SIZE_FIELD_NUMBER = 5;
    private serializers.protobuf.media.MediaContentHolder.Image.Size size_;
    public boolean hasSize() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public serializers.protobuf.media.MediaContentHolder.Image.Size getSize() {
      return size_;
    }
    
    private void initFields() {
      uri_ = "";
      title_ = "";
      width_ = 0;
      height_ = 0;
      size_ = serializers.protobuf.media.MediaContentHolder.Image.Size.SMALL;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWidth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUriBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, width_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, height_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, size_.getNumber());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUriBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, width_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, height_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, size_.getNumber());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(serializers.protobuf.media.MediaContentHolder.Image prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          serializers.protobuf.media.MediaContentHolder.Image, Builder>
        implements serializers.protobuf.media.MediaContentHolder.ImageOrBuilder {
      // Construct using serializers.protobuf.media.MediaContentHolder.Image.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uri_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        width_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        size_ = serializers.protobuf.media.MediaContentHolder.Image.Size.SMALL;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public serializers.protobuf.media.MediaContentHolder.Image getDefaultInstanceForType() {
        return serializers.protobuf.media.MediaContentHolder.Image.getDefaultInstance();
      }
      
      public serializers.protobuf.media.MediaContentHolder.Image build() {
        serializers.protobuf.media.MediaContentHolder.Image result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private serializers.protobuf.media.MediaContentHolder.Image buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        serializers.protobuf.media.MediaContentHolder.Image result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public serializers.protobuf.media.MediaContentHolder.Image buildPartial() {
        serializers.protobuf.media.MediaContentHolder.Image result = new serializers.protobuf.media.MediaContentHolder.Image(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uri_ = uri_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.size_ = size_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(serializers.protobuf.media.MediaContentHolder.Image other) {
        if (other == serializers.protobuf.media.MediaContentHolder.Image.getDefaultInstance()) return this;
        if (other.hasUri()) {
          setUri(other.getUri());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUri()) {
          
          return false;
        }
        if (!hasWidth()) {
          
          return false;
        }
        if (!hasHeight()) {
          
          return false;
        }
        if (!hasSize()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uri_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              width_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              height_ = input.readInt32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              serializers.protobuf.media.MediaContentHolder.Image.Size value = serializers.protobuf.media.MediaContentHolder.Image.Size.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000010;
                size_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string uri = 1;
      private java.lang.Object uri_ = "";
      public boolean hasUri() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUri(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uri_ = value;
        
        return this;
      }
      public Builder clearUri() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uri_ = getDefaultInstance().getUri();
        
        return this;
      }
      void setUri(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        uri_ = value;
        
      }
      
      // optional string title = 2;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        title_ = value;
        
      }
      
      // required int32 width = 3;
      private int width_ ;
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getWidth() {
        return width_;
      }
      public Builder setWidth(int value) {
        bitField0_ |= 0x00000004;
        width_ = value;
        
        return this;
      }
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        width_ = 0;
        
        return this;
      }
      
      // required int32 height = 4;
      private int height_ ;
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getHeight() {
        return height_;
      }
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000008;
        height_ = value;
        
        return this;
      }
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000008);
        height_ = 0;
        
        return this;
      }
      
      // required .serializers.protobuf.media.Image.Size size = 5;
      private serializers.protobuf.media.MediaContentHolder.Image.Size size_ = serializers.protobuf.media.MediaContentHolder.Image.Size.SMALL;
      public boolean hasSize() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public serializers.protobuf.media.MediaContentHolder.Image.Size getSize() {
        return size_;
      }
      public Builder setSize(serializers.protobuf.media.MediaContentHolder.Image.Size value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        size_ = value;
        
        return this;
      }
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000010);
        size_ = serializers.protobuf.media.MediaContentHolder.Image.Size.SMALL;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:serializers.protobuf.media.Image)
    }
    
    static {
      defaultInstance = new Image(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:serializers.protobuf.media.Image)
  }
  
  public interface MediaOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string uri = 1;
    boolean hasUri();
    String getUri();
    
    // optional string title = 2;
    boolean hasTitle();
    String getTitle();
    
    // required int32 width = 3;
    boolean hasWidth();
    int getWidth();
    
    // required int32 height = 4;
    boolean hasHeight();
    int getHeight();
    
    // required string format = 5;
    boolean hasFormat();
    String getFormat();
    
    // required int64 duration = 6;
    boolean hasDuration();
    long getDuration();
    
    // required int64 size = 7;
    boolean hasSize();
    long getSize();
    
    // optional int32 bitrate = 8;
    boolean hasBitrate();
    int getBitrate();
    
    // repeated string person = 9;
    java.util.List<String> getPersonList();
    int getPersonCount();
    String getPerson(int index);
    
    // required .serializers.protobuf.media.Media.Player player = 10;
    boolean hasPlayer();
    serializers.protobuf.media.MediaContentHolder.Media.Player getPlayer();
    
    // optional string copyright = 11;
    boolean hasCopyright();
    String getCopyright();
  }
  public static final class Media extends
      com.google.protobuf.GeneratedMessageLite
      implements MediaOrBuilder {
    // Use Media.newBuilder() to construct.
    private Media(Builder builder) {
      super(builder);
    }
    private Media(boolean noInit) {}
    
    private static final Media defaultInstance;
    public static Media getDefaultInstance() {
      return defaultInstance;
    }
    
    public Media getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum Player
        implements com.google.protobuf.Internal.EnumLite {
      JAVA(0, 0),
      FLASH(1, 1),
      ;
      
      public static final int JAVA_VALUE = 0;
      public static final int FLASH_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Player valueOf(int value) {
        switch (value) {
          case 0: return JAVA;
          case 1: return FLASH;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Player>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Player>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Player>() {
              public Player findValueByNumber(int number) {
                return Player.valueOf(number);
              }
            };
      
      private final int value;
      
      private Player(int index, int value) {
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:serializers.protobuf.media.Media.Player)
    }
    
    private int bitField0_;
    // required string uri = 1;
    public static final int URI_FIELD_NUMBER = 1;
    private java.lang.Object uri_;
    public boolean hasUri() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uri_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 width = 3;
    public static final int WIDTH_FIELD_NUMBER = 3;
    private int width_;
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getWidth() {
      return width_;
    }
    
    // required int32 height = 4;
    public static final int HEIGHT_FIELD_NUMBER = 4;
    private int height_;
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getHeight() {
      return height_;
    }
    
    // required string format = 5;
    public static final int FORMAT_FIELD_NUMBER = 5;
    private java.lang.Object format_;
    public boolean hasFormat() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getFormat() {
      java.lang.Object ref = format_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          format_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFormatBytes() {
      java.lang.Object ref = format_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        format_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 duration = 6;
    public static final int DURATION_FIELD_NUMBER = 6;
    private long duration_;
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getDuration() {
      return duration_;
    }
    
    // required int64 size = 7;
    public static final int SIZE_FIELD_NUMBER = 7;
    private long size_;
    public boolean hasSize() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public long getSize() {
      return size_;
    }
    
    // optional int32 bitrate = 8;
    public static final int BITRATE_FIELD_NUMBER = 8;
    private int bitrate_;
    public boolean hasBitrate() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getBitrate() {
      return bitrate_;
    }
    
    // repeated string person = 9;
    public static final int PERSON_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList person_;
    public java.util.List<String>
        getPersonList() {
      return person_;
    }
    public int getPersonCount() {
      return person_.size();
    }
    public String getPerson(int index) {
      return person_.get(index);
    }
    
    // required .serializers.protobuf.media.Media.Player player = 10;
    public static final int PLAYER_FIELD_NUMBER = 10;
    private serializers.protobuf.media.MediaContentHolder.Media.Player player_;
    public boolean hasPlayer() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public serializers.protobuf.media.MediaContentHolder.Media.Player getPlayer() {
      return player_;
    }
    
    // optional string copyright = 11;
    public static final int COPYRIGHT_FIELD_NUMBER = 11;
    private java.lang.Object copyright_;
    public boolean hasCopyright() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getCopyright() {
      java.lang.Object ref = copyright_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          copyright_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCopyrightBytes() {
      java.lang.Object ref = copyright_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        copyright_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      uri_ = "";
      title_ = "";
      width_ = 0;
      height_ = 0;
      format_ = "";
      duration_ = 0L;
      size_ = 0L;
      bitrate_ = 0;
      person_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      player_ = serializers.protobuf.media.MediaContentHolder.Media.Player.JAVA;
      copyright_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWidth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFormat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDuration()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUriBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, width_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, height_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getFormatBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, duration_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, size_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, bitrate_);
      }
      for (int i = 0; i < person_.size(); i++) {
        output.writeBytes(9, person_.getByteString(i));
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeEnum(10, player_.getNumber());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(11, getCopyrightBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUriBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, width_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, height_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getFormatBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, duration_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, size_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, bitrate_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < person_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(person_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPersonList().size();
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, player_.getNumber());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getCopyrightBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(serializers.protobuf.media.MediaContentHolder.Media prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          serializers.protobuf.media.MediaContentHolder.Media, Builder>
        implements serializers.protobuf.media.MediaContentHolder.MediaOrBuilder {
      // Construct using serializers.protobuf.media.MediaContentHolder.Media.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uri_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        width_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        format_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        duration_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        size_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        bitrate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        person_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        player_ = serializers.protobuf.media.MediaContentHolder.Media.Player.JAVA;
        bitField0_ = (bitField0_ & ~0x00000200);
        copyright_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public serializers.protobuf.media.MediaContentHolder.Media getDefaultInstanceForType() {
        return serializers.protobuf.media.MediaContentHolder.Media.getDefaultInstance();
      }
      
      public serializers.protobuf.media.MediaContentHolder.Media build() {
        serializers.protobuf.media.MediaContentHolder.Media result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private serializers.protobuf.media.MediaContentHolder.Media buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        serializers.protobuf.media.MediaContentHolder.Media result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public serializers.protobuf.media.MediaContentHolder.Media buildPartial() {
        serializers.protobuf.media.MediaContentHolder.Media result = new serializers.protobuf.media.MediaContentHolder.Media(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uri_ = uri_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.format_ = format_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.duration_ = duration_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.size_ = size_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.bitrate_ = bitrate_;
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          person_ = new com.google.protobuf.UnmodifiableLazyStringList(
              person_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.person_ = person_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.player_ = player_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.copyright_ = copyright_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(serializers.protobuf.media.MediaContentHolder.Media other) {
        if (other == serializers.protobuf.media.MediaContentHolder.Media.getDefaultInstance()) return this;
        if (other.hasUri()) {
          setUri(other.getUri());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasFormat()) {
          setFormat(other.getFormat());
        }
        if (other.hasDuration()) {
          setDuration(other.getDuration());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasBitrate()) {
          setBitrate(other.getBitrate());
        }
        if (!other.person_.isEmpty()) {
          if (person_.isEmpty()) {
            person_ = other.person_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensurePersonIsMutable();
            person_.addAll(other.person_);
          }
          
        }
        if (other.hasPlayer()) {
          setPlayer(other.getPlayer());
        }
        if (other.hasCopyright()) {
          setCopyright(other.getCopyright());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUri()) {
          
          return false;
        }
        if (!hasWidth()) {
          
          return false;
        }
        if (!hasHeight()) {
          
          return false;
        }
        if (!hasFormat()) {
          
          return false;
        }
        if (!hasDuration()) {
          
          return false;
        }
        if (!hasSize()) {
          
          return false;
        }
        if (!hasPlayer()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uri_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              width_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              height_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              format_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              duration_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              size_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              bitrate_ = input.readInt32();
              break;
            }
            case 74: {
              ensurePersonIsMutable();
              person_.add(input.readBytes());
              break;
            }
            case 80: {
              int rawValue = input.readEnum();
              serializers.protobuf.media.MediaContentHolder.Media.Player value = serializers.protobuf.media.MediaContentHolder.Media.Player.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000200;
                player_ = value;
              }
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              copyright_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string uri = 1;
      private java.lang.Object uri_ = "";
      public boolean hasUri() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUri(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uri_ = value;
        
        return this;
      }
      public Builder clearUri() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uri_ = getDefaultInstance().getUri();
        
        return this;
      }
      void setUri(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        uri_ = value;
        
      }
      
      // optional string title = 2;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        title_ = value;
        
      }
      
      // required int32 width = 3;
      private int width_ ;
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getWidth() {
        return width_;
      }
      public Builder setWidth(int value) {
        bitField0_ |= 0x00000004;
        width_ = value;
        
        return this;
      }
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        width_ = 0;
        
        return this;
      }
      
      // required int32 height = 4;
      private int height_ ;
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getHeight() {
        return height_;
      }
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000008;
        height_ = value;
        
        return this;
      }
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000008);
        height_ = 0;
        
        return this;
      }
      
      // required string format = 5;
      private java.lang.Object format_ = "";
      public boolean hasFormat() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getFormat() {
        java.lang.Object ref = format_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          format_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFormat(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        format_ = value;
        
        return this;
      }
      public Builder clearFormat() {
        bitField0_ = (bitField0_ & ~0x00000010);
        format_ = getDefaultInstance().getFormat();
        
        return this;
      }
      void setFormat(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        format_ = value;
        
      }
      
      // required int64 duration = 6;
      private long duration_ ;
      public boolean hasDuration() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getDuration() {
        return duration_;
      }
      public Builder setDuration(long value) {
        bitField0_ |= 0x00000020;
        duration_ = value;
        
        return this;
      }
      public Builder clearDuration() {
        bitField0_ = (bitField0_ & ~0x00000020);
        duration_ = 0L;
        
        return this;
      }
      
      // required int64 size = 7;
      private long size_ ;
      public boolean hasSize() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public long getSize() {
        return size_;
      }
      public Builder setSize(long value) {
        bitField0_ |= 0x00000040;
        size_ = value;
        
        return this;
      }
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000040);
        size_ = 0L;
        
        return this;
      }
      
      // optional int32 bitrate = 8;
      private int bitrate_ ;
      public boolean hasBitrate() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getBitrate() {
        return bitrate_;
      }
      public Builder setBitrate(int value) {
        bitField0_ |= 0x00000080;
        bitrate_ = value;
        
        return this;
      }
      public Builder clearBitrate() {
        bitField0_ = (bitField0_ & ~0x00000080);
        bitrate_ = 0;
        
        return this;
      }
      
      // repeated string person = 9;
      private com.google.protobuf.LazyStringList person_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          person_ = new com.google.protobuf.LazyStringArrayList(person_);
          bitField0_ |= 0x00000100;
         }
      }
      public java.util.List<String>
          getPersonList() {
        return java.util.Collections.unmodifiableList(person_);
      }
      public int getPersonCount() {
        return person_.size();
      }
      public String getPerson(int index) {
        return person_.get(index);
      }
      public Builder setPerson(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePersonIsMutable();
        person_.set(index, value);
        
        return this;
      }
      public Builder addPerson(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePersonIsMutable();
        person_.add(value);
        
        return this;
      }
      public Builder addAllPerson(
          java.lang.Iterable<String> values) {
        ensurePersonIsMutable();
        super.addAll(values, person_);
        
        return this;
      }
      public Builder clearPerson() {
        person_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        
        return this;
      }
      void addPerson(com.google.protobuf.ByteString value) {
        ensurePersonIsMutable();
        person_.add(value);
        
      }
      
      // required .serializers.protobuf.media.Media.Player player = 10;
      private serializers.protobuf.media.MediaContentHolder.Media.Player player_ = serializers.protobuf.media.MediaContentHolder.Media.Player.JAVA;
      public boolean hasPlayer() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public serializers.protobuf.media.MediaContentHolder.Media.Player getPlayer() {
        return player_;
      }
      public Builder setPlayer(serializers.protobuf.media.MediaContentHolder.Media.Player value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000200;
        player_ = value;
        
        return this;
      }
      public Builder clearPlayer() {
        bitField0_ = (bitField0_ & ~0x00000200);
        player_ = serializers.protobuf.media.MediaContentHolder.Media.Player.JAVA;
        
        return this;
      }
      
      // optional string copyright = 11;
      private java.lang.Object copyright_ = "";
      public boolean hasCopyright() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getCopyright() {
        java.lang.Object ref = copyright_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          copyright_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCopyright(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        copyright_ = value;
        
        return this;
      }
      public Builder clearCopyright() {
        bitField0_ = (bitField0_ & ~0x00000400);
        copyright_ = getDefaultInstance().getCopyright();
        
        return this;
      }
      void setCopyright(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        copyright_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:serializers.protobuf.media.Media)
    }
    
    static {
      defaultInstance = new Media(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:serializers.protobuf.media.Media)
  }
  
  public interface MediaContentOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated .serializers.protobuf.media.Image image = 1;
    java.util.List<serializers.protobuf.media.MediaContentHolder.Image> 
        getImageList();
    serializers.protobuf.media.MediaContentHolder.Image getImage(int index);
    int getImageCount();
    
    // required .serializers.protobuf.media.Media media = 2;
    boolean hasMedia();
    serializers.protobuf.media.MediaContentHolder.Media getMedia();
  }
  public static final class MediaContent extends
      com.google.protobuf.GeneratedMessageLite
      implements MediaContentOrBuilder {
    // Use MediaContent.newBuilder() to construct.
    private MediaContent(Builder builder) {
      super(builder);
    }
    private MediaContent(boolean noInit) {}
    
    private static final MediaContent defaultInstance;
    public static MediaContent getDefaultInstance() {
      return defaultInstance;
    }
    
    public MediaContent getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // repeated .serializers.protobuf.media.Image image = 1;
    public static final int IMAGE_FIELD_NUMBER = 1;
    private java.util.List<serializers.protobuf.media.MediaContentHolder.Image> image_;
    public java.util.List<serializers.protobuf.media.MediaContentHolder.Image> getImageList() {
      return image_;
    }
    public java.util.List<? extends serializers.protobuf.media.MediaContentHolder.ImageOrBuilder> 
        getImageOrBuilderList() {
      return image_;
    }
    public int getImageCount() {
      return image_.size();
    }
    public serializers.protobuf.media.MediaContentHolder.Image getImage(int index) {
      return image_.get(index);
    }
    public serializers.protobuf.media.MediaContentHolder.ImageOrBuilder getImageOrBuilder(
        int index) {
      return image_.get(index);
    }
    
    // required .serializers.protobuf.media.Media media = 2;
    public static final int MEDIA_FIELD_NUMBER = 2;
    private serializers.protobuf.media.MediaContentHolder.Media media_;
    public boolean hasMedia() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public serializers.protobuf.media.MediaContentHolder.Media getMedia() {
      return media_;
    }
    
    private void initFields() {
      image_ = java.util.Collections.emptyList();
      media_ = serializers.protobuf.media.MediaContentHolder.Media.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMedia()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getImageCount(); i++) {
        if (!getImage(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!getMedia().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < image_.size(); i++) {
        output.writeMessage(1, image_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, media_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < image_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, image_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, media_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(serializers.protobuf.media.MediaContentHolder.MediaContent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          serializers.protobuf.media.MediaContentHolder.MediaContent, Builder>
        implements serializers.protobuf.media.MediaContentHolder.MediaContentOrBuilder {
      // Construct using serializers.protobuf.media.MediaContentHolder.MediaContent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        image_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        media_ = serializers.protobuf.media.MediaContentHolder.Media.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public serializers.protobuf.media.MediaContentHolder.MediaContent getDefaultInstanceForType() {
        return serializers.protobuf.media.MediaContentHolder.MediaContent.getDefaultInstance();
      }
      
      public serializers.protobuf.media.MediaContentHolder.MediaContent build() {
        serializers.protobuf.media.MediaContentHolder.MediaContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private serializers.protobuf.media.MediaContentHolder.MediaContent buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        serializers.protobuf.media.MediaContentHolder.MediaContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public serializers.protobuf.media.MediaContentHolder.MediaContent buildPartial() {
        serializers.protobuf.media.MediaContentHolder.MediaContent result = new serializers.protobuf.media.MediaContentHolder.MediaContent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          image_ = java.util.Collections.unmodifiableList(image_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.image_ = image_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.media_ = media_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(serializers.protobuf.media.MediaContentHolder.MediaContent other) {
        if (other == serializers.protobuf.media.MediaContentHolder.MediaContent.getDefaultInstance()) return this;
        if (!other.image_.isEmpty()) {
          if (image_.isEmpty()) {
            image_ = other.image_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureImageIsMutable();
            image_.addAll(other.image_);
          }
          
        }
        if (other.hasMedia()) {
          mergeMedia(other.getMedia());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMedia()) {
          
          return false;
        }
        for (int i = 0; i < getImageCount(); i++) {
          if (!getImage(i).isInitialized()) {
            
            return false;
          }
        }
        if (!getMedia().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              serializers.protobuf.media.MediaContentHolder.Image.Builder subBuilder = serializers.protobuf.media.MediaContentHolder.Image.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addImage(subBuilder.buildPartial());
              break;
            }
            case 18: {
              serializers.protobuf.media.MediaContentHolder.Media.Builder subBuilder = serializers.protobuf.media.MediaContentHolder.Media.newBuilder();
              if (hasMedia()) {
                subBuilder.mergeFrom(getMedia());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMedia(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .serializers.protobuf.media.Image image = 1;
      private java.util.List<serializers.protobuf.media.MediaContentHolder.Image> image_ =
        java.util.Collections.emptyList();
      private void ensureImageIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          image_ = new java.util.ArrayList<serializers.protobuf.media.MediaContentHolder.Image>(image_);
          bitField0_ |= 0x00000001;
         }
      }
      
      public java.util.List<serializers.protobuf.media.MediaContentHolder.Image> getImageList() {
        return java.util.Collections.unmodifiableList(image_);
      }
      public int getImageCount() {
        return image_.size();
      }
      public serializers.protobuf.media.MediaContentHolder.Image getImage(int index) {
        return image_.get(index);
      }
      public Builder setImage(
          int index, serializers.protobuf.media.MediaContentHolder.Image value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImageIsMutable();
        image_.set(index, value);
        
        return this;
      }
      public Builder setImage(
          int index, serializers.protobuf.media.MediaContentHolder.Image.Builder builderForValue) {
        ensureImageIsMutable();
        image_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addImage(serializers.protobuf.media.MediaContentHolder.Image value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImageIsMutable();
        image_.add(value);
        
        return this;
      }
      public Builder addImage(
          int index, serializers.protobuf.media.MediaContentHolder.Image value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImageIsMutable();
        image_.add(index, value);
        
        return this;
      }
      public Builder addImage(
          serializers.protobuf.media.MediaContentHolder.Image.Builder builderForValue) {
        ensureImageIsMutable();
        image_.add(builderForValue.build());
        
        return this;
      }
      public Builder addImage(
          int index, serializers.protobuf.media.MediaContentHolder.Image.Builder builderForValue) {
        ensureImageIsMutable();
        image_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllImage(
          java.lang.Iterable<? extends serializers.protobuf.media.MediaContentHolder.Image> values) {
        ensureImageIsMutable();
        super.addAll(values, image_);
        
        return this;
      }
      public Builder clearImage() {
        image_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      public Builder removeImage(int index) {
        ensureImageIsMutable();
        image_.remove(index);
        
        return this;
      }
      
      // required .serializers.protobuf.media.Media media = 2;
      private serializers.protobuf.media.MediaContentHolder.Media media_ = serializers.protobuf.media.MediaContentHolder.Media.getDefaultInstance();
      public boolean hasMedia() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public serializers.protobuf.media.MediaContentHolder.Media getMedia() {
        return media_;
      }
      public Builder setMedia(serializers.protobuf.media.MediaContentHolder.Media value) {
        if (value == null) {
          throw new NullPointerException();
        }
        media_ = value;
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setMedia(
          serializers.protobuf.media.MediaContentHolder.Media.Builder builderForValue) {
        media_ = builderForValue.build();
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeMedia(serializers.protobuf.media.MediaContentHolder.Media value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            media_ != serializers.protobuf.media.MediaContentHolder.Media.getDefaultInstance()) {
          media_ =
            serializers.protobuf.media.MediaContentHolder.Media.newBuilder(media_).mergeFrom(value).buildPartial();
        } else {
          media_ = value;
        }
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearMedia() {
        media_ = serializers.protobuf.media.MediaContentHolder.Media.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:serializers.protobuf.media.MediaContent)
    }
    
    static {
      defaultInstance = new MediaContent(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:serializers.protobuf.media.MediaContent)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
