// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/media.proto

package serializers.protobuf.media;

public final class MediaContentHolder {
  private MediaContentHolder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ImageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string uri = 1;
    boolean hasUri();
    String getUri();
    
    // optional string title = 2;
    boolean hasTitle();
    String getTitle();
    
    // required int32 width = 3;
    boolean hasWidth();
    int getWidth();
    
    // required int32 height = 4;
    boolean hasHeight();
    int getHeight();
    
    // required .serializers.protobuf.media.Image.Size size = 5;
    boolean hasSize();
    serializers.protobuf.media.MediaContentHolder.Image.Size getSize();
  }
  public static final class Image extends
      com.google.protobuf.GeneratedMessage
      implements ImageOrBuilder {
    // Use Image.newBuilder() to construct.
    private Image(Builder builder) {
      super(builder);
    }
    private Image(boolean noInit) {}
    
    private static final Image defaultInstance;
    public static Image getDefaultInstance() {
      return defaultInstance;
    }
    
    public Image getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serializers.protobuf.media.MediaContentHolder.internal_static_serializers_protobuf_media_Image_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serializers.protobuf.media.MediaContentHolder.internal_static_serializers_protobuf_media_Image_fieldAccessorTable;
    }
    
    public enum Size
        implements com.google.protobuf.ProtocolMessageEnum {
      SMALL(0, 0),
      LARGE(1, 1),
      ;
      
      public static final int SMALL_VALUE = 0;
      public static final int LARGE_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Size valueOf(int value) {
        switch (value) {
          case 0: return SMALL;
          case 1: return LARGE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Size>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Size>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Size>() {
              public Size findValueByNumber(int number) {
                return Size.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return serializers.protobuf.media.MediaContentHolder.Image.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Size[] VALUES = {
        SMALL, LARGE, 
      };
      
      public static Size valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Size(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:serializers.protobuf.media.Image.Size)
    }
    
    private int bitField0_;
    // required string uri = 1;
    public static final int URI_FIELD_NUMBER = 1;
    private java.lang.Object uri_;
    public boolean hasUri() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uri_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 width = 3;
    public static final int WIDTH_FIELD_NUMBER = 3;
    private int width_;
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getWidth() {
      return width_;
    }
    
    // required int32 height = 4;
    public static final int HEIGHT_FIELD_NUMBER = 4;
    private int height_;
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getHeight() {
      return height_;
    }
    
    // required .serializers.protobuf.media.Image.Size size = 5;
    public static final int SIZE_FIELD_NUMBER = 5;
    private serializers.protobuf.media.MediaContentHolder.Image.Size size_;
    public boolean hasSize() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public serializers.protobuf.media.MediaContentHolder.Image.Size getSize() {
      return size_;
    }
    
    private void initFields() {
      uri_ = "";
      title_ = "";
      width_ = 0;
      height_ = 0;
      size_ = serializers.protobuf.media.MediaContentHolder.Image.Size.SMALL;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWidth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUriBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, width_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, height_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, size_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUriBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, width_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, height_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, size_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Image parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(serializers.protobuf.media.MediaContentHolder.Image prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements serializers.protobuf.media.MediaContentHolder.ImageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return serializers.protobuf.media.MediaContentHolder.internal_static_serializers_protobuf_media_Image_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return serializers.protobuf.media.MediaContentHolder.internal_static_serializers_protobuf_media_Image_fieldAccessorTable;
      }
      
      // Construct using serializers.protobuf.media.MediaContentHolder.Image.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uri_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        width_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        size_ = serializers.protobuf.media.MediaContentHolder.Image.Size.SMALL;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serializers.protobuf.media.MediaContentHolder.Image.getDescriptor();
      }
      
      public serializers.protobuf.media.MediaContentHolder.Image getDefaultInstanceForType() {
        return serializers.protobuf.media.MediaContentHolder.Image.getDefaultInstance();
      }
      
      public serializers.protobuf.media.MediaContentHolder.Image build() {
        serializers.protobuf.media.MediaContentHolder.Image result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private serializers.protobuf.media.MediaContentHolder.Image buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        serializers.protobuf.media.MediaContentHolder.Image result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public serializers.protobuf.media.MediaContentHolder.Image buildPartial() {
        serializers.protobuf.media.MediaContentHolder.Image result = new serializers.protobuf.media.MediaContentHolder.Image(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uri_ = uri_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.size_ = size_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof serializers.protobuf.media.MediaContentHolder.Image) {
          return mergeFrom((serializers.protobuf.media.MediaContentHolder.Image)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(serializers.protobuf.media.MediaContentHolder.Image other) {
        if (other == serializers.protobuf.media.MediaContentHolder.Image.getDefaultInstance()) return this;
        if (other.hasUri()) {
          setUri(other.getUri());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUri()) {
          
          return false;
        }
        if (!hasWidth()) {
          
          return false;
        }
        if (!hasHeight()) {
          
          return false;
        }
        if (!hasSize()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uri_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              width_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              height_ = input.readInt32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              serializers.protobuf.media.MediaContentHolder.Image.Size value = serializers.protobuf.media.MediaContentHolder.Image.Size.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                size_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string uri = 1;
      private java.lang.Object uri_ = "";
      public boolean hasUri() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUri(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uri_ = value;
        onChanged();
        return this;
      }
      public Builder clearUri() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      void setUri(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        uri_ = value;
        onChanged();
      }
      
      // optional string title = 2;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
      }
      
      // required int32 width = 3;
      private int width_ ;
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getWidth() {
        return width_;
      }
      public Builder setWidth(int value) {
        bitField0_ |= 0x00000004;
        width_ = value;
        onChanged();
        return this;
      }
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        width_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 height = 4;
      private int height_ ;
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getHeight() {
        return height_;
      }
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000008;
        height_ = value;
        onChanged();
        return this;
      }
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000008);
        height_ = 0;
        onChanged();
        return this;
      }
      
      // required .serializers.protobuf.media.Image.Size size = 5;
      private serializers.protobuf.media.MediaContentHolder.Image.Size size_ = serializers.protobuf.media.MediaContentHolder.Image.Size.SMALL;
      public boolean hasSize() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public serializers.protobuf.media.MediaContentHolder.Image.Size getSize() {
        return size_;
      }
      public Builder setSize(serializers.protobuf.media.MediaContentHolder.Image.Size value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        size_ = value;
        onChanged();
        return this;
      }
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000010);
        size_ = serializers.protobuf.media.MediaContentHolder.Image.Size.SMALL;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:serializers.protobuf.media.Image)
    }
    
    static {
      defaultInstance = new Image(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:serializers.protobuf.media.Image)
  }
  
  public interface MediaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string uri = 1;
    boolean hasUri();
    String getUri();
    
    // optional string title = 2;
    boolean hasTitle();
    String getTitle();
    
    // required int32 width = 3;
    boolean hasWidth();
    int getWidth();
    
    // required int32 height = 4;
    boolean hasHeight();
    int getHeight();
    
    // required string format = 5;
    boolean hasFormat();
    String getFormat();
    
    // required int64 duration = 6;
    boolean hasDuration();
    long getDuration();
    
    // required int64 size = 7;
    boolean hasSize();
    long getSize();
    
    // optional int32 bitrate = 8;
    boolean hasBitrate();
    int getBitrate();
    
    // repeated string person = 9;
    java.util.List<String> getPersonList();
    int getPersonCount();
    String getPerson(int index);
    
    // required .serializers.protobuf.media.Media.Player player = 10;
    boolean hasPlayer();
    serializers.protobuf.media.MediaContentHolder.Media.Player getPlayer();
    
    // optional string copyright = 11;
    boolean hasCopyright();
    String getCopyright();
  }
  public static final class Media extends
      com.google.protobuf.GeneratedMessage
      implements MediaOrBuilder {
    // Use Media.newBuilder() to construct.
    private Media(Builder builder) {
      super(builder);
    }
    private Media(boolean noInit) {}
    
    private static final Media defaultInstance;
    public static Media getDefaultInstance() {
      return defaultInstance;
    }
    
    public Media getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serializers.protobuf.media.MediaContentHolder.internal_static_serializers_protobuf_media_Media_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serializers.protobuf.media.MediaContentHolder.internal_static_serializers_protobuf_media_Media_fieldAccessorTable;
    }
    
    public enum Player
        implements com.google.protobuf.ProtocolMessageEnum {
      JAVA(0, 0),
      FLASH(1, 1),
      ;
      
      public static final int JAVA_VALUE = 0;
      public static final int FLASH_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Player valueOf(int value) {
        switch (value) {
          case 0: return JAVA;
          case 1: return FLASH;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Player>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Player>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Player>() {
              public Player findValueByNumber(int number) {
                return Player.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return serializers.protobuf.media.MediaContentHolder.Media.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Player[] VALUES = {
        JAVA, FLASH, 
      };
      
      public static Player valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Player(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:serializers.protobuf.media.Media.Player)
    }
    
    private int bitField0_;
    // required string uri = 1;
    public static final int URI_FIELD_NUMBER = 1;
    private java.lang.Object uri_;
    public boolean hasUri() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uri_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 width = 3;
    public static final int WIDTH_FIELD_NUMBER = 3;
    private int width_;
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getWidth() {
      return width_;
    }
    
    // required int32 height = 4;
    public static final int HEIGHT_FIELD_NUMBER = 4;
    private int height_;
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getHeight() {
      return height_;
    }
    
    // required string format = 5;
    public static final int FORMAT_FIELD_NUMBER = 5;
    private java.lang.Object format_;
    public boolean hasFormat() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getFormat() {
      java.lang.Object ref = format_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          format_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFormatBytes() {
      java.lang.Object ref = format_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        format_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 duration = 6;
    public static final int DURATION_FIELD_NUMBER = 6;
    private long duration_;
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getDuration() {
      return duration_;
    }
    
    // required int64 size = 7;
    public static final int SIZE_FIELD_NUMBER = 7;
    private long size_;
    public boolean hasSize() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public long getSize() {
      return size_;
    }
    
    // optional int32 bitrate = 8;
    public static final int BITRATE_FIELD_NUMBER = 8;
    private int bitrate_;
    public boolean hasBitrate() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getBitrate() {
      return bitrate_;
    }
    
    // repeated string person = 9;
    public static final int PERSON_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList person_;
    public java.util.List<String>
        getPersonList() {
      return person_;
    }
    public int getPersonCount() {
      return person_.size();
    }
    public String getPerson(int index) {
      return person_.get(index);
    }
    
    // required .serializers.protobuf.media.Media.Player player = 10;
    public static final int PLAYER_FIELD_NUMBER = 10;
    private serializers.protobuf.media.MediaContentHolder.Media.Player player_;
    public boolean hasPlayer() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public serializers.protobuf.media.MediaContentHolder.Media.Player getPlayer() {
      return player_;
    }
    
    // optional string copyright = 11;
    public static final int COPYRIGHT_FIELD_NUMBER = 11;
    private java.lang.Object copyright_;
    public boolean hasCopyright() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getCopyright() {
      java.lang.Object ref = copyright_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          copyright_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCopyrightBytes() {
      java.lang.Object ref = copyright_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        copyright_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      uri_ = "";
      title_ = "";
      width_ = 0;
      height_ = 0;
      format_ = "";
      duration_ = 0L;
      size_ = 0L;
      bitrate_ = 0;
      person_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      player_ = serializers.protobuf.media.MediaContentHolder.Media.Player.JAVA;
      copyright_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWidth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFormat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDuration()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUriBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, width_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, height_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getFormatBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, duration_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, size_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, bitrate_);
      }
      for (int i = 0; i < person_.size(); i++) {
        output.writeBytes(9, person_.getByteString(i));
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeEnum(10, player_.getNumber());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(11, getCopyrightBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUriBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, width_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, height_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getFormatBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, duration_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, size_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, bitrate_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < person_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(person_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPersonList().size();
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, player_.getNumber());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getCopyrightBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.Media parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(serializers.protobuf.media.MediaContentHolder.Media prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements serializers.protobuf.media.MediaContentHolder.MediaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return serializers.protobuf.media.MediaContentHolder.internal_static_serializers_protobuf_media_Media_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return serializers.protobuf.media.MediaContentHolder.internal_static_serializers_protobuf_media_Media_fieldAccessorTable;
      }
      
      // Construct using serializers.protobuf.media.MediaContentHolder.Media.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uri_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        width_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        format_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        duration_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        size_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        bitrate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        person_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        player_ = serializers.protobuf.media.MediaContentHolder.Media.Player.JAVA;
        bitField0_ = (bitField0_ & ~0x00000200);
        copyright_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serializers.protobuf.media.MediaContentHolder.Media.getDescriptor();
      }
      
      public serializers.protobuf.media.MediaContentHolder.Media getDefaultInstanceForType() {
        return serializers.protobuf.media.MediaContentHolder.Media.getDefaultInstance();
      }
      
      public serializers.protobuf.media.MediaContentHolder.Media build() {
        serializers.protobuf.media.MediaContentHolder.Media result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private serializers.protobuf.media.MediaContentHolder.Media buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        serializers.protobuf.media.MediaContentHolder.Media result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public serializers.protobuf.media.MediaContentHolder.Media buildPartial() {
        serializers.protobuf.media.MediaContentHolder.Media result = new serializers.protobuf.media.MediaContentHolder.Media(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uri_ = uri_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.format_ = format_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.duration_ = duration_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.size_ = size_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.bitrate_ = bitrate_;
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          person_ = new com.google.protobuf.UnmodifiableLazyStringList(
              person_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.person_ = person_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.player_ = player_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.copyright_ = copyright_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof serializers.protobuf.media.MediaContentHolder.Media) {
          return mergeFrom((serializers.protobuf.media.MediaContentHolder.Media)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(serializers.protobuf.media.MediaContentHolder.Media other) {
        if (other == serializers.protobuf.media.MediaContentHolder.Media.getDefaultInstance()) return this;
        if (other.hasUri()) {
          setUri(other.getUri());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasFormat()) {
          setFormat(other.getFormat());
        }
        if (other.hasDuration()) {
          setDuration(other.getDuration());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasBitrate()) {
          setBitrate(other.getBitrate());
        }
        if (!other.person_.isEmpty()) {
          if (person_.isEmpty()) {
            person_ = other.person_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensurePersonIsMutable();
            person_.addAll(other.person_);
          }
          onChanged();
        }
        if (other.hasPlayer()) {
          setPlayer(other.getPlayer());
        }
        if (other.hasCopyright()) {
          setCopyright(other.getCopyright());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUri()) {
          
          return false;
        }
        if (!hasWidth()) {
          
          return false;
        }
        if (!hasHeight()) {
          
          return false;
        }
        if (!hasFormat()) {
          
          return false;
        }
        if (!hasDuration()) {
          
          return false;
        }
        if (!hasSize()) {
          
          return false;
        }
        if (!hasPlayer()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uri_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              width_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              height_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              format_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              duration_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              size_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              bitrate_ = input.readInt32();
              break;
            }
            case 74: {
              ensurePersonIsMutable();
              person_.add(input.readBytes());
              break;
            }
            case 80: {
              int rawValue = input.readEnum();
              serializers.protobuf.media.MediaContentHolder.Media.Player value = serializers.protobuf.media.MediaContentHolder.Media.Player.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(10, rawValue);
              } else {
                bitField0_ |= 0x00000200;
                player_ = value;
              }
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              copyright_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string uri = 1;
      private java.lang.Object uri_ = "";
      public boolean hasUri() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUri(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uri_ = value;
        onChanged();
        return this;
      }
      public Builder clearUri() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      void setUri(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        uri_ = value;
        onChanged();
      }
      
      // optional string title = 2;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
      }
      
      // required int32 width = 3;
      private int width_ ;
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getWidth() {
        return width_;
      }
      public Builder setWidth(int value) {
        bitField0_ |= 0x00000004;
        width_ = value;
        onChanged();
        return this;
      }
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        width_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 height = 4;
      private int height_ ;
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getHeight() {
        return height_;
      }
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000008;
        height_ = value;
        onChanged();
        return this;
      }
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000008);
        height_ = 0;
        onChanged();
        return this;
      }
      
      // required string format = 5;
      private java.lang.Object format_ = "";
      public boolean hasFormat() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getFormat() {
        java.lang.Object ref = format_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          format_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFormat(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        format_ = value;
        onChanged();
        return this;
      }
      public Builder clearFormat() {
        bitField0_ = (bitField0_ & ~0x00000010);
        format_ = getDefaultInstance().getFormat();
        onChanged();
        return this;
      }
      void setFormat(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        format_ = value;
        onChanged();
      }
      
      // required int64 duration = 6;
      private long duration_ ;
      public boolean hasDuration() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getDuration() {
        return duration_;
      }
      public Builder setDuration(long value) {
        bitField0_ |= 0x00000020;
        duration_ = value;
        onChanged();
        return this;
      }
      public Builder clearDuration() {
        bitField0_ = (bitField0_ & ~0x00000020);
        duration_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 size = 7;
      private long size_ ;
      public boolean hasSize() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public long getSize() {
        return size_;
      }
      public Builder setSize(long value) {
        bitField0_ |= 0x00000040;
        size_ = value;
        onChanged();
        return this;
      }
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000040);
        size_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int32 bitrate = 8;
      private int bitrate_ ;
      public boolean hasBitrate() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getBitrate() {
        return bitrate_;
      }
      public Builder setBitrate(int value) {
        bitField0_ |= 0x00000080;
        bitrate_ = value;
        onChanged();
        return this;
      }
      public Builder clearBitrate() {
        bitField0_ = (bitField0_ & ~0x00000080);
        bitrate_ = 0;
        onChanged();
        return this;
      }
      
      // repeated string person = 9;
      private com.google.protobuf.LazyStringList person_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          person_ = new com.google.protobuf.LazyStringArrayList(person_);
          bitField0_ |= 0x00000100;
         }
      }
      public java.util.List<String>
          getPersonList() {
        return java.util.Collections.unmodifiableList(person_);
      }
      public int getPersonCount() {
        return person_.size();
      }
      public String getPerson(int index) {
        return person_.get(index);
      }
      public Builder setPerson(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePersonIsMutable();
        person_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addPerson(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePersonIsMutable();
        person_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllPerson(
          java.lang.Iterable<String> values) {
        ensurePersonIsMutable();
        super.addAll(values, person_);
        onChanged();
        return this;
      }
      public Builder clearPerson() {
        person_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      void addPerson(com.google.protobuf.ByteString value) {
        ensurePersonIsMutable();
        person_.add(value);
        onChanged();
      }
      
      // required .serializers.protobuf.media.Media.Player player = 10;
      private serializers.protobuf.media.MediaContentHolder.Media.Player player_ = serializers.protobuf.media.MediaContentHolder.Media.Player.JAVA;
      public boolean hasPlayer() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public serializers.protobuf.media.MediaContentHolder.Media.Player getPlayer() {
        return player_;
      }
      public Builder setPlayer(serializers.protobuf.media.MediaContentHolder.Media.Player value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000200;
        player_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayer() {
        bitField0_ = (bitField0_ & ~0x00000200);
        player_ = serializers.protobuf.media.MediaContentHolder.Media.Player.JAVA;
        onChanged();
        return this;
      }
      
      // optional string copyright = 11;
      private java.lang.Object copyright_ = "";
      public boolean hasCopyright() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getCopyright() {
        java.lang.Object ref = copyright_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          copyright_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCopyright(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        copyright_ = value;
        onChanged();
        return this;
      }
      public Builder clearCopyright() {
        bitField0_ = (bitField0_ & ~0x00000400);
        copyright_ = getDefaultInstance().getCopyright();
        onChanged();
        return this;
      }
      void setCopyright(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        copyright_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:serializers.protobuf.media.Media)
    }
    
    static {
      defaultInstance = new Media(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:serializers.protobuf.media.Media)
  }
  
  public interface MediaContentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .serializers.protobuf.media.Image image = 1;
    java.util.List<serializers.protobuf.media.MediaContentHolder.Image> 
        getImageList();
    serializers.protobuf.media.MediaContentHolder.Image getImage(int index);
    int getImageCount();
    java.util.List<? extends serializers.protobuf.media.MediaContentHolder.ImageOrBuilder> 
        getImageOrBuilderList();
    serializers.protobuf.media.MediaContentHolder.ImageOrBuilder getImageOrBuilder(
        int index);
    
    // required .serializers.protobuf.media.Media media = 2;
    boolean hasMedia();
    serializers.protobuf.media.MediaContentHolder.Media getMedia();
    serializers.protobuf.media.MediaContentHolder.MediaOrBuilder getMediaOrBuilder();
  }
  public static final class MediaContent extends
      com.google.protobuf.GeneratedMessage
      implements MediaContentOrBuilder {
    // Use MediaContent.newBuilder() to construct.
    private MediaContent(Builder builder) {
      super(builder);
    }
    private MediaContent(boolean noInit) {}
    
    private static final MediaContent defaultInstance;
    public static MediaContent getDefaultInstance() {
      return defaultInstance;
    }
    
    public MediaContent getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serializers.protobuf.media.MediaContentHolder.internal_static_serializers_protobuf_media_MediaContent_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serializers.protobuf.media.MediaContentHolder.internal_static_serializers_protobuf_media_MediaContent_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated .serializers.protobuf.media.Image image = 1;
    public static final int IMAGE_FIELD_NUMBER = 1;
    private java.util.List<serializers.protobuf.media.MediaContentHolder.Image> image_;
    public java.util.List<serializers.protobuf.media.MediaContentHolder.Image> getImageList() {
      return image_;
    }
    public java.util.List<? extends serializers.protobuf.media.MediaContentHolder.ImageOrBuilder> 
        getImageOrBuilderList() {
      return image_;
    }
    public int getImageCount() {
      return image_.size();
    }
    public serializers.protobuf.media.MediaContentHolder.Image getImage(int index) {
      return image_.get(index);
    }
    public serializers.protobuf.media.MediaContentHolder.ImageOrBuilder getImageOrBuilder(
        int index) {
      return image_.get(index);
    }
    
    // required .serializers.protobuf.media.Media media = 2;
    public static final int MEDIA_FIELD_NUMBER = 2;
    private serializers.protobuf.media.MediaContentHolder.Media media_;
    public boolean hasMedia() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public serializers.protobuf.media.MediaContentHolder.Media getMedia() {
      return media_;
    }
    public serializers.protobuf.media.MediaContentHolder.MediaOrBuilder getMediaOrBuilder() {
      return media_;
    }
    
    private void initFields() {
      image_ = java.util.Collections.emptyList();
      media_ = serializers.protobuf.media.MediaContentHolder.Media.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMedia()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getImageCount(); i++) {
        if (!getImage(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!getMedia().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < image_.size(); i++) {
        output.writeMessage(1, image_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, media_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < image_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, image_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, media_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.media.MediaContentHolder.MediaContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(serializers.protobuf.media.MediaContentHolder.MediaContent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements serializers.protobuf.media.MediaContentHolder.MediaContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return serializers.protobuf.media.MediaContentHolder.internal_static_serializers_protobuf_media_MediaContent_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return serializers.protobuf.media.MediaContentHolder.internal_static_serializers_protobuf_media_MediaContent_fieldAccessorTable;
      }
      
      // Construct using serializers.protobuf.media.MediaContentHolder.MediaContent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getImageFieldBuilder();
          getMediaFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (imageBuilder_ == null) {
          image_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          imageBuilder_.clear();
        }
        if (mediaBuilder_ == null) {
          media_ = serializers.protobuf.media.MediaContentHolder.Media.getDefaultInstance();
        } else {
          mediaBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serializers.protobuf.media.MediaContentHolder.MediaContent.getDescriptor();
      }
      
      public serializers.protobuf.media.MediaContentHolder.MediaContent getDefaultInstanceForType() {
        return serializers.protobuf.media.MediaContentHolder.MediaContent.getDefaultInstance();
      }
      
      public serializers.protobuf.media.MediaContentHolder.MediaContent build() {
        serializers.protobuf.media.MediaContentHolder.MediaContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private serializers.protobuf.media.MediaContentHolder.MediaContent buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        serializers.protobuf.media.MediaContentHolder.MediaContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public serializers.protobuf.media.MediaContentHolder.MediaContent buildPartial() {
        serializers.protobuf.media.MediaContentHolder.MediaContent result = new serializers.protobuf.media.MediaContentHolder.MediaContent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (imageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            image_ = java.util.Collections.unmodifiableList(image_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.image_ = image_;
        } else {
          result.image_ = imageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        if (mediaBuilder_ == null) {
          result.media_ = media_;
        } else {
          result.media_ = mediaBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof serializers.protobuf.media.MediaContentHolder.MediaContent) {
          return mergeFrom((serializers.protobuf.media.MediaContentHolder.MediaContent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(serializers.protobuf.media.MediaContentHolder.MediaContent other) {
        if (other == serializers.protobuf.media.MediaContentHolder.MediaContent.getDefaultInstance()) return this;
        if (imageBuilder_ == null) {
          if (!other.image_.isEmpty()) {
            if (image_.isEmpty()) {
              image_ = other.image_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureImageIsMutable();
              image_.addAll(other.image_);
            }
            onChanged();
          }
        } else {
          if (!other.image_.isEmpty()) {
            if (imageBuilder_.isEmpty()) {
              imageBuilder_.dispose();
              imageBuilder_ = null;
              image_ = other.image_;
              bitField0_ = (bitField0_ & ~0x00000001);
              imageBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getImageFieldBuilder() : null;
            } else {
              imageBuilder_.addAllMessages(other.image_);
            }
          }
        }
        if (other.hasMedia()) {
          mergeMedia(other.getMedia());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMedia()) {
          
          return false;
        }
        for (int i = 0; i < getImageCount(); i++) {
          if (!getImage(i).isInitialized()) {
            
            return false;
          }
        }
        if (!getMedia().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              serializers.protobuf.media.MediaContentHolder.Image.Builder subBuilder = serializers.protobuf.media.MediaContentHolder.Image.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addImage(subBuilder.buildPartial());
              break;
            }
            case 18: {
              serializers.protobuf.media.MediaContentHolder.Media.Builder subBuilder = serializers.protobuf.media.MediaContentHolder.Media.newBuilder();
              if (hasMedia()) {
                subBuilder.mergeFrom(getMedia());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMedia(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .serializers.protobuf.media.Image image = 1;
      private java.util.List<serializers.protobuf.media.MediaContentHolder.Image> image_ =
        java.util.Collections.emptyList();
      private void ensureImageIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          image_ = new java.util.ArrayList<serializers.protobuf.media.MediaContentHolder.Image>(image_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          serializers.protobuf.media.MediaContentHolder.Image, serializers.protobuf.media.MediaContentHolder.Image.Builder, serializers.protobuf.media.MediaContentHolder.ImageOrBuilder> imageBuilder_;
      
      public java.util.List<serializers.protobuf.media.MediaContentHolder.Image> getImageList() {
        if (imageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(image_);
        } else {
          return imageBuilder_.getMessageList();
        }
      }
      public int getImageCount() {
        if (imageBuilder_ == null) {
          return image_.size();
        } else {
          return imageBuilder_.getCount();
        }
      }
      public serializers.protobuf.media.MediaContentHolder.Image getImage(int index) {
        if (imageBuilder_ == null) {
          return image_.get(index);
        } else {
          return imageBuilder_.getMessage(index);
        }
      }
      public Builder setImage(
          int index, serializers.protobuf.media.MediaContentHolder.Image value) {
        if (imageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImageIsMutable();
          image_.set(index, value);
          onChanged();
        } else {
          imageBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setImage(
          int index, serializers.protobuf.media.MediaContentHolder.Image.Builder builderForValue) {
        if (imageBuilder_ == null) {
          ensureImageIsMutable();
          image_.set(index, builderForValue.build());
          onChanged();
        } else {
          imageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addImage(serializers.protobuf.media.MediaContentHolder.Image value) {
        if (imageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImageIsMutable();
          image_.add(value);
          onChanged();
        } else {
          imageBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addImage(
          int index, serializers.protobuf.media.MediaContentHolder.Image value) {
        if (imageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImageIsMutable();
          image_.add(index, value);
          onChanged();
        } else {
          imageBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addImage(
          serializers.protobuf.media.MediaContentHolder.Image.Builder builderForValue) {
        if (imageBuilder_ == null) {
          ensureImageIsMutable();
          image_.add(builderForValue.build());
          onChanged();
        } else {
          imageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addImage(
          int index, serializers.protobuf.media.MediaContentHolder.Image.Builder builderForValue) {
        if (imageBuilder_ == null) {
          ensureImageIsMutable();
          image_.add(index, builderForValue.build());
          onChanged();
        } else {
          imageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllImage(
          java.lang.Iterable<? extends serializers.protobuf.media.MediaContentHolder.Image> values) {
        if (imageBuilder_ == null) {
          ensureImageIsMutable();
          super.addAll(values, image_);
          onChanged();
        } else {
          imageBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearImage() {
        if (imageBuilder_ == null) {
          image_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          imageBuilder_.clear();
        }
        return this;
      }
      public Builder removeImage(int index) {
        if (imageBuilder_ == null) {
          ensureImageIsMutable();
          image_.remove(index);
          onChanged();
        } else {
          imageBuilder_.remove(index);
        }
        return this;
      }
      public serializers.protobuf.media.MediaContentHolder.Image.Builder getImageBuilder(
          int index) {
        return getImageFieldBuilder().getBuilder(index);
      }
      public serializers.protobuf.media.MediaContentHolder.ImageOrBuilder getImageOrBuilder(
          int index) {
        if (imageBuilder_ == null) {
          return image_.get(index);  } else {
          return imageBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends serializers.protobuf.media.MediaContentHolder.ImageOrBuilder> 
           getImageOrBuilderList() {
        if (imageBuilder_ != null) {
          return imageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(image_);
        }
      }
      public serializers.protobuf.media.MediaContentHolder.Image.Builder addImageBuilder() {
        return getImageFieldBuilder().addBuilder(
            serializers.protobuf.media.MediaContentHolder.Image.getDefaultInstance());
      }
      public serializers.protobuf.media.MediaContentHolder.Image.Builder addImageBuilder(
          int index) {
        return getImageFieldBuilder().addBuilder(
            index, serializers.protobuf.media.MediaContentHolder.Image.getDefaultInstance());
      }
      public java.util.List<serializers.protobuf.media.MediaContentHolder.Image.Builder> 
           getImageBuilderList() {
        return getImageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          serializers.protobuf.media.MediaContentHolder.Image, serializers.protobuf.media.MediaContentHolder.Image.Builder, serializers.protobuf.media.MediaContentHolder.ImageOrBuilder> 
          getImageFieldBuilder() {
        if (imageBuilder_ == null) {
          imageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              serializers.protobuf.media.MediaContentHolder.Image, serializers.protobuf.media.MediaContentHolder.Image.Builder, serializers.protobuf.media.MediaContentHolder.ImageOrBuilder>(
                  image_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          image_ = null;
        }
        return imageBuilder_;
      }
      
      // required .serializers.protobuf.media.Media media = 2;
      private serializers.protobuf.media.MediaContentHolder.Media media_ = serializers.protobuf.media.MediaContentHolder.Media.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          serializers.protobuf.media.MediaContentHolder.Media, serializers.protobuf.media.MediaContentHolder.Media.Builder, serializers.protobuf.media.MediaContentHolder.MediaOrBuilder> mediaBuilder_;
      public boolean hasMedia() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public serializers.protobuf.media.MediaContentHolder.Media getMedia() {
        if (mediaBuilder_ == null) {
          return media_;
        } else {
          return mediaBuilder_.getMessage();
        }
      }
      public Builder setMedia(serializers.protobuf.media.MediaContentHolder.Media value) {
        if (mediaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          media_ = value;
          onChanged();
        } else {
          mediaBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setMedia(
          serializers.protobuf.media.MediaContentHolder.Media.Builder builderForValue) {
        if (mediaBuilder_ == null) {
          media_ = builderForValue.build();
          onChanged();
        } else {
          mediaBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeMedia(serializers.protobuf.media.MediaContentHolder.Media value) {
        if (mediaBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              media_ != serializers.protobuf.media.MediaContentHolder.Media.getDefaultInstance()) {
            media_ =
              serializers.protobuf.media.MediaContentHolder.Media.newBuilder(media_).mergeFrom(value).buildPartial();
          } else {
            media_ = value;
          }
          onChanged();
        } else {
          mediaBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearMedia() {
        if (mediaBuilder_ == null) {
          media_ = serializers.protobuf.media.MediaContentHolder.Media.getDefaultInstance();
          onChanged();
        } else {
          mediaBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public serializers.protobuf.media.MediaContentHolder.Media.Builder getMediaBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMediaFieldBuilder().getBuilder();
      }
      public serializers.protobuf.media.MediaContentHolder.MediaOrBuilder getMediaOrBuilder() {
        if (mediaBuilder_ != null) {
          return mediaBuilder_.getMessageOrBuilder();
        } else {
          return media_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          serializers.protobuf.media.MediaContentHolder.Media, serializers.protobuf.media.MediaContentHolder.Media.Builder, serializers.protobuf.media.MediaContentHolder.MediaOrBuilder> 
          getMediaFieldBuilder() {
        if (mediaBuilder_ == null) {
          mediaBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              serializers.protobuf.media.MediaContentHolder.Media, serializers.protobuf.media.MediaContentHolder.Media.Builder, serializers.protobuf.media.MediaContentHolder.MediaOrBuilder>(
                  media_,
                  getParentForChildren(),
                  isClean());
          media_ = null;
        }
        return mediaBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:serializers.protobuf.media.MediaContent)
    }
    
    static {
      defaultInstance = new MediaContent(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:serializers.protobuf.media.MediaContent)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_serializers_protobuf_media_Image_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serializers_protobuf_media_Image_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_serializers_protobuf_media_Media_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serializers_protobuf_media_Media_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_serializers_protobuf_media_MediaContent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serializers_protobuf_media_MediaContent_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022schema/media.proto\022\032serializers.protob" +
      "uf.media\"\226\001\n\005Image\022\013\n\003uri\030\001 \002(\t\022\r\n\005title" +
      "\030\002 \001(\t\022\r\n\005width\030\003 \002(\005\022\016\n\006height\030\004 \002(\005\0224\n" +
      "\004size\030\005 \002(\0162&.serializers.protobuf.media" +
      ".Image.Size\"\034\n\004Size\022\t\n\005SMALL\020\000\022\t\n\005LARGE\020" +
      "\001\"\377\001\n\005Media\022\013\n\003uri\030\001 \002(\t\022\r\n\005title\030\002 \001(\t\022" +
      "\r\n\005width\030\003 \002(\005\022\016\n\006height\030\004 \002(\005\022\016\n\006format" +
      "\030\005 \002(\t\022\020\n\010duration\030\006 \002(\003\022\014\n\004size\030\007 \002(\003\022\017" +
      "\n\007bitrate\030\010 \001(\005\022\016\n\006person\030\t \003(\t\0228\n\006playe" +
      "r\030\n \002(\0162(.serializers.protobuf.media.Med",
      "ia.Player\022\021\n\tcopyright\030\013 \001(\t\"\035\n\006Player\022\010" +
      "\n\004JAVA\020\000\022\t\n\005FLASH\020\001\"r\n\014MediaContent\0220\n\005i" +
      "mage\030\001 \003(\0132!.serializers.protobuf.media." +
      "Image\0220\n\005media\030\002 \002(\0132!.serializers.proto" +
      "buf.media.MediaB2\n\032serializers.protobuf." +
      "mediaB\022MediaContentHolderH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_serializers_protobuf_media_Image_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_serializers_protobuf_media_Image_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_serializers_protobuf_media_Image_descriptor,
              new java.lang.String[] { "Uri", "Title", "Width", "Height", "Size", },
              serializers.protobuf.media.MediaContentHolder.Image.class,
              serializers.protobuf.media.MediaContentHolder.Image.Builder.class);
          internal_static_serializers_protobuf_media_Media_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_serializers_protobuf_media_Media_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_serializers_protobuf_media_Media_descriptor,
              new java.lang.String[] { "Uri", "Title", "Width", "Height", "Format", "Duration", "Size", "Bitrate", "Person", "Player", "Copyright", },
              serializers.protobuf.media.MediaContentHolder.Media.class,
              serializers.protobuf.media.MediaContentHolder.Media.Builder.class);
          internal_static_serializers_protobuf_media_MediaContent_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_serializers_protobuf_media_MediaContent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_serializers_protobuf_media_MediaContent_descriptor,
              new java.lang.String[] { "Image", "Media", },
              serializers.protobuf.media.MediaContentHolder.MediaContent.class,
              serializers.protobuf.media.MediaContentHolder.MediaContent.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
